sudo: required

services:
  - docker

language: ruby

before_install:
  - shopt -s expand_aliases

install:
  - docker pull lakruzz/jekyll-plus
  - alias jekyll='docker run -it -v $(pwd):/app:rw --workdir /app  lakruzz/jekyll-plus jekyll'
  - docker pull 18fgsa/html-proofer
  - alias htmlproofer='docker run -it -v $(pwd):/site --workdir /site 18fgsa/html-proofer'

before_script:

script:
  - jekyll build
  - htmlproofer --check-favicon --check-opengraph ./_site

branches:
  only:
    - master
