sudo: required

services:
  - docker

language: ruby

before_install:
  - shopt -s expand_aliases

install:
  - docker pull lakruzz/jekyll-plus
  - alias jekyll='docker run -it -v $(pwd):/app:rw --workdir /app  lakruzz/jekyll-plus jekyll'
  - docker pull 18fgsa/html-proofer
  - alias htmlproofer='docker run -it -v $(pwd):/site --workdir /site 18fgsa/html-proofer'

before_script:

script:
  - jekyll build
  - htmlproofer --check-favicon --check-opengraph ./_site

branches:
  only:
  - master

after_success:
  - echo "Built with jekyll from $(git rev-parse --short HEAD) of lakruzz/lakruzz.com" > _site/version.txt
  - cd _site
  - git init && \
  - git remote add origin https://github.com/lakruzz/lakruzz.github.io.git
  - git add -A .
  - git commit -F version.txt
  - git push -fu origin master
