#!/usr/bin/env bash
if [ $# -eq 0 ]
  then
    echo "Usage: ./serve <customer>"
else
	echo "jekyll serve --host=0.0.0.0 --config _config.yml,_customer_details/$1/_config.yml"    
	jekyll serve --host=0.0.0.0 --config _config.yml,_customer_details/$1/_config.yml
fi
